"""add image fields to service comments

Revision ID: 6e6483e4f080
Revises: 6e228a5724e1
Create Date: 2026-07-06 12:21:39.911589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6483e4f080'
down_revision = '6e228a5724e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_public_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_comments', schema=None) as batch_op:
        batch_op.drop_column('image_public_id')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
