"""empty message

Revision ID: ed0b6a8b58c0
Revises: e67db382851a
Create Date: 2026-06-26 17:07:15.619886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed0b6a8b58c0'
down_revision = 'e67db382851a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('service_status_logs')
    op.drop_table('services')
    op.drop_table('service_comments')
    op.drop_table('customers')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('address')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('role')
        batch_op.drop_column('specialty')
        batch_op.drop_column('job_position')
        batch_op.drop_column('city')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('workshop_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(batch_op.f('users_employee_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workshops', ['workshop_id'], ['id'])
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('workshops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.alter_column('cif',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshops', schema=None) as batch_op:
        batch_op.alter_column('cif',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('website')
        batch_op.drop_column('country')
        batch_op.drop_column('province')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_employee_id_fkey'), 'employees', ['employee_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('users_employee_id_key'), ['employee_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('workshop_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('job_position', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('driving_license', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('workshop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('customers_workshop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey')),
    sa.UniqueConstraint('dni', name=op.f('customers_dni_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('driving_license', name=op.f('customers_driving_license_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('service_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('comment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('service_comments_employee_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('service_comments_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_comments_pkey'))
    )
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('entry_mileage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('observations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workshop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('services_customer_id_fkey')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('services_employee_id_fkey')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('services_vehicle_id_fkey')),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('services_workshop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('services_pkey'))
    )
    op.create_table('service_status_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('service_status_logs_employee_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('service_status_logs_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_status_logs_pkey'))
    )
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plate', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('vin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fuel_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('power_hp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine_cc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workshop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('vehicles_customer_id_fkey')),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('vehicles_workshop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey')),
    sa.UniqueConstraint('plate', name=op.f('vehicles_plate_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('vin', name=op.f('vehicles_vin_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
